### DISCUSSION TITLE
Modify CSS for green line that appears when dragging a block into the canvas

### DISCUSSION THREAD

**Discussion by HashimHaider** [GrapesJS/grapesjs#3833] [Q&A] [answered]
Hi guys!
Is there a class that I could possibly overwrite to update the styles for the green line as shown in the screenshot?
The line appears when dragging a block into the canvas. I've tried inspecting different elements to figure out if there's a class that I could overwrite, but have had no luck so far. TIA!

![grapesjs-discussion-ss](https://user-images.githubusercontent.com/81612773/135235236-3fb6b4e1-5ef7-432e-bb68-bcd23aac0aa7.png)
!

**Comment by HashimHaider** [comment]
Ping

**Comment by artf** [comment, marked as answer]
This is how you would change the color of the placeholder.
```css
.gjs-placeholder.horizontal {
   border-color: transparent red;
}
.gjs-placeholder.vertical {
   border-color: red transparent;
}
.gjs-placeholder-int {
   background-color: red;
}
```

**Reply by HashimHaider** [reply]
Works like a charm, thank you!

**Reply by FawadOmerEsk** [reply]
Not working for me. Any ideas as to why that could be?
Grapesjs v0.19.5

**Reply by ronaldohoch** [reply]
@FawadOmerEsk this worked to me.:

```css
.gjs-placeholder.horizontal,
.gjs-com-placeholder.horizontal,
.gjs-placeholder.horizontal {
    border-color: rgba(0, 0, 0, 0) red;
}

.gjs-placeholder.vertical,
.gjs-com-placeholder.vertical,
.gjs-placeholder.vertical {
    border-color: red rgba(0, 0, 0, 0);
}

.gjs-placeholder-int,
.gjs-com-placeholder-int,
.gjs-placeholder-int {
    background-color: red/*#62c462;*/
}

```
