### DISCUSSION TITLE
Keyframes with CssComposer?

### DISCUSSION THREAD

**Discussion by ronaldohoch** [GrapesJS/grapesjs#4778] [Q&A] [answered]
Hello Arthur and other contributors!

I recently discovered `editor.CssComposer.setRule` and I wanted to know if there is a way to use this API to add keyFrames to the document, like:
```css
    @-webkit-keyframes fadeIn {
      0% {
        opacity: 0
      }

      to {
        opacity: 1
      }
    }
 ```

Edit: It's related to this issue: https://github.com/artf/grapesjs/issues/4771
