### DISCUSSION TITLE
Preserve Body ID and Style in Page Manager

### DISCUSSION THREAD

**Discussion by michaelhofer-slg** [GrapesJS/grapesjs#5127] [Q&A]
We use the internal page manager to create multiple pages of a control panel. Our editor is configured with the following settings:

```
avoidInlineStyle: true,
protectedCss: "",
exportWrapper: 1,
domComponents: {
    storeWrapper: 1
}
```

When setting the background color of the body, we get the following generated HTML and CSS:

```html
<body id="iie6"></body>
```

```css
body{width:1920px;height:1080px;}#iie6{width:1920px;height:1080px;background-color:#09c931;}
```

However, when we load the page, the background color is lost since the wrapper (`body` in our case) has a new ID. 

Is there a way to preserve the body ID when loading it?
