### DISCUSSION TITLE
Change of --gjs-main-fon has no effect

### DISCUSSION THREAD

**Discussion by dohomi** [GrapesJS/grapesjs#5839] [Q&A]
Hi Guys

I would like to simply change the main font to only one font ( I don't allow changing fonts ). The font should be my system font "Inter"
```css
:root{
    --gjs-main-font: Inter, -apple-system, system-ui, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
}
```
Even this rule is applied I still see the font-family of 'Times'. What am I missing here?

Additionally I also tried to change the fontProperty:
```ts
   const StyleManager = editor.StyleManager
          const fontProperty = StyleManager.getProperty("typography", "font-family")
          if (fontProperty) {
            fontProperty.set("default", "Inter, sans-serif")
            StyleManager.render()
          }
```

I found many issues of changing the options of font-family but none of the solutions were helping me out yet.
