### DISCUSSION TITLE
How to show notification dot on the sectors

### DISCUSSION THREAD

**Discussion by asimex** [GrapesJS/grapesjs#5970] [Q&A] [answered]
<img width="242" alt="Screenshot 2024-06-26 at 3 04 31 AM" src="https://github.com/GrapesJS/grapesjs/assets/38231806/219c87af-3734-4fc6-9928-80068d182955">

how to show these notification dot like you guys are showing on the studio version.

**Comment by mosh-tudor** [comment, marked as answer]
@asimex 

Using `:has` you can achieve something like this:
```css
.gjs-sm-sector .gjs-sm-sector-label {
    margin-right: 0.3em
}
.gjs-sm-sector .gjs-sm-sector-title::before,
.gjs-sm-sector .gjs-sm-sector-title::after {
    content: '•';
    display: none;
    margin-left: 0.1em;
    order: 5;
}
.gjs-sm-sector:has(.gjs-sm-label.gjs-four-color) .gjs-sm-sector-title::before {
    display: block;
    color: var(--gjs-quaternary-color);
}
.gjs-sm-sector:has(.gjs-sm-label.gjs-color-warn) .gjs-sm-sector-title::after {
    display: block;
    color: var(--gjs-color-warn);
}

```
<img width="230" alt="Screenshot 2024-06-28 at 10 16 17" src="https://github.com/GrapesJS/grapesjs/assets/668451/6546f8df-c369-4924-988a-c5179bcfa31e">
